### ISSUE TITLE
.npy camera parameters

### ISSUE THREAD

**Issue by wynsmile** [BillyXYB/FDNeRF#2]
Dear author, thank you very much for your excellent work, I want to use my own data, How to get .npy camera parameters? Looking forward to your reply.

**Comment by ZHANG1023** [comment]
Please refer to the Data preparation section of our readme file.

**Comment by wynsmile** [comment]
Thank you, I have solved it, but now I have encountered another problem, and the error message is as follows: 
Traceback (most recent call last):
    return ctx.invoke(self.callback, **ctx.params)
  File "..envs\xxx\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "run.py", line 172, in run
    w_plus = w_plus_editor.project(G, c, outdir, id_image, device=torch.device('cuda'), w_avg_samples=600,
  File "...editors\w_plus_editor.py", line 245, in project
    loss.backward(retain_graph=True)
  File "..envs\xxx\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "...envs\xxx\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'PowBackward0' returned nan values in its 0th output.
What is the reason for this?
